export class Receipts{
    receiptId: number;
    sponsorId: number;
    rdate: string;
    firstName: string;
    middleName: string; 
    lastName: string;
    fullName: string;
    transaction: string;
    amount: number
    initiativeId: number
    initiativeName: string;
    parishName: string;
    orgName: string;
    receiptType: number;
    referenceId: number;
    city: string;
    state: string;
    zipCode: string;
    centerId: number;
    parishId: number;
    email1: string;
    email2: string;
    phone1: string;
    phone2: string;
    type: number
    createdDate: string
    createdby: number;
    updatedBy: number;
    status: number;
    streetAddress: string;
}